### ISSUE TITLE
Path of gm is incorrect on Debian

### ISSUE THREAD

**Issue by map7** [antoinelyset/poleica#5]
I'm using Debian Jessie on my servers and the gm binary is in /usr/bin/gm not /usr/local/bin/gm where poleica is looking for it. Hence I get this error;

```
>> Poleica.new(p.full_path).to_png
RuntimeError: graphics_magick not found @ /usr/local/bin/gm
	from /usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/poleica-0.10.4/lib/poleica/converters/utils.rb:32:in `bin_path'
	from /usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/poleica-0.10.4/lib/poleica/converters/graphics_magick/graphics_magick.rb:24:in `to_png'
	from /usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/poleica-0.10.4/lib/poleica/converters/convertible.rb:18:in `convert_to_extension'
	from /usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/poleica-0.10.4/lib/poleica/converters/convertible.rb:12:in `method_missing'
	from (irb):4
	from /usr/local/rbenv/versions/1.9.3-p551/bin/irb:12:in `<main>'
```

In the meantime I've just symlinked my /usr/bin/gm to /usr/local/bin/gm as a workaround.

**Comment by antoinelyset** [comment]
Hi Michael,

These things are tricky, so I made an option to choose where you want Poleica to search the binary. You should be good with : 

```ruby
Poleica.configure do |config|
  config.libre_office[:bin_paths][:linux] = '/usr/bin/gm'
end
```
https://github.com/antoinelyset/poleica#configuration
